insert into authors (id, first_name, last_name) values (1, 'Willyt', 'Pleavin');
insert into authors (id, first_name, last_name) values (2, 'Brew', 'Ughi');
insert into authors (id, first_name, last_name) values (3, 'Judith', 'Amyes');
insert into authors (id, first_name, last_name) values (4, 'Pasquale', 'Bramall');
insert into authors (id, first_name, last_name) values (5, 'Myrtie', 'Jovey');
insert into authors (id, first_name, last_name) values (6, 'Ailsun', 'Georghiou');
insert into authors (id, first_name, last_name) values (7, 'Melisse', 'Sked');
insert into authors (id, first_name, last_name) values (8, 'Kimberli', 'Daughtry');
insert into authors (id, first_name, last_name) values (9, 'Jaimie', 'Follan');
insert into authors (id, first_name, last_name) values (10, 'Micaela', 'Siggee');
insert into authors (id, first_name, last_name) values (11, 'Lek', 'Thring');
insert into authors (id, first_name, last_name) values (12, 'Pattin', 'Rudeyeard');
insert into authors (id, first_name, last_name) values (13, 'Ethe', 'Lidgate');
insert into authors (id, first_name, last_name) values (14, 'Bentley', 'Taggert');
insert into authors (id, first_name, last_name) values (15, 'Marlowe', 'Gorrick');
insert into authors (id, first_name, last_name) values (16, 'Justine', 'Yockley');
insert into authors (id, first_name, last_name) values (17, 'Parrnell', 'Houdmont');
insert into authors (id, first_name, last_name) values (18, 'Berkeley', 'Biswell');
insert into authors (id, first_name, last_name) values (19, 'Lida', 'Champneys');
insert into authors (id, first_name, last_name) values (20, 'Janela', 'Antoniades');
insert into authors (id, first_name, last_name) values (21, 'Starlin', 'Gullifant');

insert into books (id, price, price_old, title, author_id) values (1, 595, 2102, 'Konklab', 8);
insert into books (id, price, price_old, title, author_id) values (2, 693, 2812, 'Regrant', 7);
insert into books (id, price, price_old, title, author_id) values (3, 1706, 2850, 'Kanlam', 16);
insert into books (id, price, price_old, title, author_id) values (4, 2365, 3713, 'Sub-Ex', 18);
insert into books (id, price, price_old, title, author_id) values (5, 2798, 2884, 'Stronghold', 8);
insert into books (id, price, price_old, title, author_id) values (6, 2586, 2495, 'Cardify', 16);
insert into books (id, price, price_old, title, author_id) values (7, 2021, 1467, 'Wrapsafe', 4);
insert into books (id, price, price_old, title, author_id) values (8, 2275, 1631, 'Fix San', 12);
insert into books (id, price, price_old, title, author_id) values (9, 2049, 1223, 'Cardguard', 18);
insert into books (id, price, price_old, title, author_id) values (10, 2394, 1363, 'Home Ing', 20);
insert into books (id, price, price_old, title, author_id) values (11, 1798, 1765, 'Stim', 4);
insert into books (id, price, price_old, title, author_id) values (12, 2594, 3625, 'Cardify', 14);
insert into books (id, price, price_old, title, author_id) values (13, 1947, 2946, 'Stim', 15);
insert into books (id, price, price_old, title, author_id) values (14, 2480, 1215, 'Toughjoyfax', 1);
insert into books (id, price, price_old, title, author_id) values (15, 816, 3681, 'Bitwolf', 16);
insert into books (id, price, price_old, title, author_id) values (16, 1438, 1502, 'Regrant', 3);
insert into books (id, price, price_old, title, author_id) values (17, 1395, 3101, 'It', 5);
insert into books (id, price, price_old, title, author_id) values (18, 1153, 1393, 'Lotstring', 2);
insert into books (id, price, price_old, title, author_id) values (19, 2663, 1160, 'Andalax', 6);
insert into books (id, price, price_old, title, author_id) values (20, 1360, 3947, 'Keylex', 1);
insert into books (id, price, price_old, title, author_id) values (21, 2950, 3230, 'Mat Lam Tam', 9);
